version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend/Trabalho_3_Bruno
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Frontend/Trabalho_3_Bruno:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend/Trabalho_3_Bruno/Trabalho_3_Bruno
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Backend/Trabalho_3_Bruno:/app
